name: projet
description: Application de flashcards avec fonctionnalités avancées pour l'apprentissage et la mémorisation.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
    
  # Gestion d'état
  provider: ^6.0.0
  
  # Base de données et stockage
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.0.0  # Support pour desktop
  path_provider: ^2.0.2
  shared_preferences: ^2.0.15
  localstorage: ^4.0.1+4  # Stockage web
  
  # UI et design
  flutter_svg: ^1.0.0
  flutter_colorpicker: ^1.0.3
  
  # Utilitaires et formatage
  intl: ^0.17.0
  uuid: ^3.0.7  # Version corrigée
  csv: ^5.1.1
  
  # Fonctionnalités desktop et mobile
  window_manager: ^0.3.0
  file_picker: ^6.1.1
  share_plus: ^10.1.4
  
  # Audio
  just_audio: ^0.9.36
  record: ^5.0.4
  
  # Firebase (optionnel)
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
